[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "BumpBlaster5000"
version = "0.0.1"
authors = [
    {name = "Mark Plitt", email = "markplitt@gmail.com"},
]
description = "Drosophila central complex imaging and behavior control"
readme = "README.md"
license = {text = "BSD"}
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Topic :: Utilities",
    "License :: OSI Approved :: BSD License",
]
dependencies = [
    "numpy",
    "scipy",
    "pyserial",
    "pyqtgraph",
    "PySide6",
    "ipython",
    "pandas",
    "pywin32; sys_platform == 'win32'",
    "numba",
    "pillow",
]

[tool.hatch.build.targets.wheel]
packages = ["BumpBlaster5000"]

[tool.uv]
managed = true